server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
  add-host-header: true
  sensitive-headers:  #用" "覆盖敏感头信息

leyou:
  jwt:
    pubKeyPath: /Users/luyi/IdeaProjects/leyou/rsa/rsa.pri   #公钥地址
    cookieName: leyou-token
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item